import { SellType } from '@prisma/client';
import {
  FmOrderExport,
  FmOrderItem,
  FmOrderMetaInfo,
  FmOrderOption,
  FmOrderRefund,
  FmOrderReturn,
} from '@project-lc/shared-types';

export const orderDetailOptionsSample: FmOrderOption[] = [
  {
    item_option_seq: 4,
    title1: '색상',
    option1: '그레이',
    ea: 1,
    step: '75',
    step35: 0,
    step45: 0,
    step55: 0,
    step65: 0,
    step75: 1,
    step85: 0,
    member_sale: '0.00',
    mobile_sale: null,
    price: '1000.00',
    ori_price: '1000.00',
    item_seq: 1,
  },
  {
    item_option_seq: 5,
    title1: '색상',
    option1: '화이트',
    ea: 1,
    step: '75',
    step35: 0,
    step45: 0,
    step55: 0,
    step65: 0,
    step75: 1,
    step85: 0,
    member_sale: '0.00',
    mobile_sale: null,
    price: '100.00',
    ori_price: '100.00',
    item_seq: 1,
  },
];

export const orderDetailItemsSample: Array<
  FmOrderItem & { options: FmOrderOption[]; sellType: SellType }
> = [
  {
    goods_seq: 41,
    goods_name: 'test2',
    image: '/data/goods/1/2021/07/_temp_16266708888484thumbCart.png',
    item_seq: 4,
    options: orderDetailOptionsSample,
    shipping_seq: 1,
    shipping_set_name: 'asdf',
    shipping_type: 'free',
    shipping_method: 'delivery',
    shipping_group: '43_123_delivery',
    sellType: 'normal',
  },
];

export const orderMetaInfoSample: FmOrderMetaInfo = {
  totalShippingCost: '0.00',
  totalDeliveryCost: '0.00',
  id: '2021082612090917531',
  regist_date: '2021-08-26T03:09:09.000Z',
  sitetype: 'P',
  depositor: '테스트',
  deposit_date: '2021-08-26T03:10:25.000Z',
  settleprice: '1100.00',
  step: '75',
  order_user_name: 'username',
  order_phone: '--',
  order_cellphone: '010-0000-0000',
  order_email: 'asdf@asdf.com',
  recipient_user_name: 'username',
  recipient_phone: '--',
  recipient_cellphone: '010-0000-0000',
  recipient_email: 'asdf@asdf.com',
  recipient_zipcode: '12345',
  recipient_address: 'somewhere over the rainboe',
  recipient_address_street: 'somewhere over the rainboe',
  recipient_address_detail: 'somewhere over the rainboe',
  memo: '1. 배송메모 : 1234,',
  order_seq: 'asdf',
  shipping_seq: '1,2',
  shippings: [
    {
      shipping_seq: 1,
      deliveryCost: '2500',
      delivery_cost: '2500',
      shippingCost: '2500',
      shipping_cost: '2500',
      shipping_group: 'asdf',
      shipping_method: 'delivery',
      shipping_set_name: '택배',
      shipping_type: 'free',
      items: orderDetailItemsSample,
    },
  ],
};

export const orderDetailExportsSample: FmOrderExport[] = [
  {
    export_code: 'D2109091123',
    export_date: '2021-09-08T15:00:00.000Z',
    complete_date: null,
    shipping_date: null,
    export_status: '55',
    delivery_company_code: 'code0',
    delivery_number: '123456789012345',
    totalEa: 1,
    itemOptions: [
      {
        goods_name: 'test2',
        image: '/data/1234.png',
        item_option_seq: 8,
        title1: '색상',
        option1: '블랙',
        ea: 1,
        price: '10.00',
        step: '55',
        export_code: 'export_code',
        goods_seq: '1',
      },
    ],
  },
];

export const orderDetailRefundsSample: FmOrderRefund[] = [
  {
    refund_code: '1234',
    refund_type: 'return',
    regist_date: '2021-08-26T06:50:15.000Z',
    refund_date: '2021-08-26T07:13:12.000Z',
    status: 'complete',
    refund_reason: '반품환불',
    manager_id: '1234',
    memail: '1234',
    mcellphone: '1234',
    totalEa: '2',
    refund_goods_price: '1100.00',
    items: [
      {
        goods_name: 'test2',
        image: '/data/1234.png',
        refund_item_seq: 2,
        item_seq: 4,
        option_seq: 4,
        ea: 1,
        item_option_seq: 4,
        title1: '색상',
        option1: '그레이',
        step: '75',
        member_sale: '0.00',
        mobile_sale: null,
        price: '1000.00',
        ori_price: '1000.00',
      },
      {
        goods_name: 'test2',
        image: '/data/1234.png',
        refund_item_seq: 3,
        item_seq: 4,
        option_seq: 5,
        ea: 1,
        item_option_seq: 5,
        title1: '색상',
        option1: '화이트',
        step: '75',
        member_sale: '0.00',
        mobile_sale: null,
        price: '100.00',
        ori_price: '100.00',
      },
    ],
  },
];

export const orderDetailReturnsSample: FmOrderReturn[] = [
  {
    return_code: '1234',
    refund_code: '1234',
    return_type: 'return',
    status: 'complete',
    regist_date: '2021-08-26T06:50:15.000Z',
    return_date: '2021-08-26T07:09:48.000Z',
    reason_desc: '사이즈가 맞지 않아요',
    return_reason: '상세사유',
    return_method: 'user',
    sender_zipcode: '12345',
    sender_address_type: 'street',
    sender_address: 'sender_address',
    sender_address_street: 'sender_address_street',
    sender_address_detail: '12345',
    phone: null,
    cellphone: '1234',
    manager_id: '1234',
    memail: '1234',
    mcellphone: '1234',
    ea: '2',
    items: [
      {
        goods_name: 'test2',
        image: '/data/1234.png',
        return_item_seq: 1,
        item_seq: 4,
        option_seq: 4,
        ea: 1,
        reason_desc: '사이즈가 맞지 않아요',
        item_option_seq: 4,
        title1: '색상',
        option1: '그레이',
        step: '75',
        member_sale: '0.00',
        mobile_sale: null,
        price: '1000.00',
        ori_price: '1000.00',
      },
      {
        goods_name: 'test2',
        image: '/data/1234.png',
        return_item_seq: 2,
        item_seq: 4,
        option_seq: 5,
        ea: 1,
        reason_desc: '사이즈가 맞지 않아요',
        item_option_seq: 5,
        title1: '색상',
        option1: '화이트',
        step: '75',
        member_sale: '0.00',
        mobile_sale: null,
        price: '100.00',
        ori_price: '100.00',
      },
    ],
  },
];
