import { FindFmOrderDetailRes } from '@project-lc/shared-types';
import { OrderSpreadSheetGenerator } from './orderSpreadSheetGenerator';

const dummies: FindFmOrderDetailRes[] = [
  {
    shipping_seq: '4',
    id: '2021082612090917531',
    regist_date: '2021-10-22T05:19:09.000Z',
    sitetype: 'P',
    depositor: '테스트',
    deposit_date: '2021-10-22T05:17:41.000Z',
    settleprice: '1100.00',
    step: '75',
    order_seq: '2021082612090917531',
    order_user_name: '강화수',
    order_phone: '--',
    order_cellphone: '010-3974-5175',
    order_email: 'iamsupermazinga@gmail.com',
    recipient_user_name: '강화수',
    recipient_phone: '--',
    recipient_cellphone: '010-3974-5175',
    recipient_email: 'iamsupermazinga@gmail.com',
    recipient_zipcode: '46291',
    recipient_address: '부산광역시 금정구 장전동 643-117 테라스파크',
    recipient_address_street: '부산광역시 금정구 장전온천천로 51 (테라스파크)',
    recipient_address_detail: '313호',
    memo: '1234',
    memoOriginal: '1234',
    totalPrice: '1100.00',
    totalEa: 2,
    totalType: 2,
    totalShippingCost: '0.00',
    totalDeliveryCost: '0.00',
    items: [
      {
        goods_seq: 41,
        goods_name: 'test2',
        image: '/data/goods/1/2021/07/_temp_16266708888484thumbCart.png',
        item_seq: 4,
        shipping_seq: 4,
        shipping_set_name: '택배',
        shipping_type: 'free',
        shipping_method: 'delivery',
        shipping_group: '1_1_delivery',
        options: [
          {
            item_option_seq: 4,
            item_seq: 4,
            title1: '색상',
            option1: '그레이',
            ea: 1,
            step: '75',
            step35: 0,
            step45: 0,
            step55: 0,
            step65: 0,
            step75: 1,
            step85: 0,
            member_sale: '0.00',
            mobile_sale: null,
            price: '1000.00',
            ori_price: '1000.00',
          },
          {
            item_option_seq: 5,
            item_seq: 4,
            title1: '색상',
            option1: '화이트',
            ea: 1,
            step: '75',
            step35: 0,
            step45: 0,
            step55: 0,
            step65: 0,
            step75: 1,
            step85: 0,
            member_sale: '0.00',
            mobile_sale: null,
            price: '100.00',
            ori_price: '100.00',
          },
        ],
      },
    ],
    exports: [
      {
        export_code: 'D210826122',
        bundle_export_code: '',
        export_date: '2021-08-25T15:00:00.000Z',
        complete_date: '2021-08-25T15:00:00.000Z',
        shipping_date: '2021-08-25T15:00:00.000Z',
        export_status: '75',
        delivery_company_code: 'code0',
        delivery_number: '12313123131313212132',
        totalEa: 2,
        itemOptions: [
          {
            goods_name: 'test2',
            image: '/data/goods/1/2021/07/_temp_16266708888484thumbCart.png',
            item_option_seq: 4,
            title1: '색상',
            option1: '그레이',
            ea: 1,
            price: '1000.00',
            step: '75',
          },
          {
            goods_name: 'test2',
            image: '/data/goods/1/2021/07/_temp_16266708888484thumbCart.png',
            item_option_seq: 5,
            title1: '색상',
            option1: '화이트',
            ea: 1,
            price: '100.00',
            step: '75',
          },
        ],
      },
    ],
    refunds: [
      {
        refund_code: 'C210826152',
        refund_type: 'return',
        regist_date: '2021-08-26T06:50:15.000Z',
        refund_date: '2021-08-26T07:13:12.000Z',
        status: 'complete',
        refund_reason: '반품환불',
        manager_id: 'kwany',
        memail: 'kwany@onad.io',
        mcellphone: '01041765342',
        totalEa: '2',
        refund_goods_price: '1100.00',
        items: [
          {
            goods_name: 'test2',
            image: '/data/goods/1/2021/07/_temp_16266708888484thumbCart.png',
            refund_item_seq: 2,
            item_seq: 4,
            option_seq: 4,
            ea: 1,
            item_option_seq: 4,
            title1: '색상',
            option1: '그레이',
            step: '75',
            member_sale: '0.00',
            mobile_sale: null,
            price: '1000.00',
            ori_price: '1000.00',
          },
          {
            goods_name: 'test2',
            image: '/data/goods/1/2021/07/_temp_16266708888484thumbCart.png',
            refund_item_seq: 3,
            item_seq: 4,
            option_seq: 5,
            ea: 1,
            item_option_seq: 5,
            title1: '색상',
            option1: '화이트',
            step: '75',
            member_sale: '0.00',
            mobile_sale: null,
            price: '100.00',
            ori_price: '100.00',
          },
        ],
      },
    ],
    returns: [
      {
        return_code: 'R210826151',
        refund_code: 'C210826152',
        return_type: 'return',
        status: 'complete',
        regist_date: '2021-08-26T06:50:15.000Z',
        return_date: '2021-08-26T07:09:48.000Z',
        reason_desc: '사이즈가 맞지 않아요',
        return_reason: '상세사유',
        return_method: 'user',
        sender_zipcode: '46291',
        sender_address_type: 'street',
        sender_address: '부산광역시 금정구 장전동 643-117 테라스파크',
        sender_address_street: '부산광역시 금정구 장전온천천로 51 (테라스파크)',
        sender_address_detail: '313호',
        phone: null,
        cellphone: '010-3974-5175',
        manager_id: 'kwany',
        memail: 'kwany@onad.io',
        mcellphone: '01041765342',
        ea: '2',
        items: [
          {
            goods_name: 'test2',
            image: '/data/goods/1/2021/07/_temp_16266708888484thumbCart.png',
            return_item_seq: 1,
            item_seq: 4,
            option_seq: 4,
            ea: 1,
            reason_desc: '사이즈가 맞지 않아요',
            item_option_seq: 4,
            title1: '색상',
            option1: '그레이',
            step: '75',
            member_sale: '0.00',
            mobile_sale: null,
            price: '1000.00',
            ori_price: '1000.00',
          },
          {
            goods_name: 'test2',
            image: '/data/goods/1/2021/07/_temp_16266708888484thumbCart.png',
            return_item_seq: 2,
            item_seq: 4,
            option_seq: 5,
            ea: 1,
            reason_desc: '사이즈가 맞지 않아요',
            item_option_seq: 5,
            title1: '색상',
            option1: '화이트',
            step: '75',
            member_sale: '0.00',
            mobile_sale: null,
            price: '100.00',
            ori_price: '100.00',
          },
        ],
      },
    ],
    shippings: [
      {
        shipping_seq: 4,
        shipping_set_name: '택배',
        shipping_type: 'free',
        shipping_method: 'delivery',
        shipping_group: '1_1_delivery',
        shipping_cost: '0.00',
        delivery_cost: '0.00',
        shippingCost: '0.00',
        deliveryCost: '0.00',
        items: [
          {
            goods_seq: 41,
            goods_name: 'test2',
            image: '/data/goods/1/2021/07/_temp_16266708888484thumbCart.png',
            item_seq: 4,
            shipping_seq: 4,
            shipping_set_name: '택배',
            shipping_type: 'free',
            shipping_method: 'delivery',
            shipping_group: '1_1_delivery',
            options: [
              {
                item_option_seq: 4,
                item_seq: 4,
                title1: '색상',
                option1: '그레이',
                ea: 1,
                step: '75',
                step35: 0,
                step45: 0,
                step55: 0,
                step65: 0,
                step75: 1,
                step85: 0,
                member_sale: '0.00',
                mobile_sale: null,
                price: '1000.00',
                ori_price: '1000.00',
              },
              {
                item_option_seq: 5,
                item_seq: 4,
                title1: '색상',
                option1: '화이트',
                ea: 1,
                step: '75',
                step35: 0,
                step45: 0,
                step55: 0,
                step65: 0,
                step75: 1,
                step85: 0,
                member_sale: '0.00',
                mobile_sale: null,
                price: '100.00',
                ori_price: '100.00',
              },
            ],
          },
        ],
      },
    ],
  },
  {
    shipping_seq: '24,24',
    id: '2021091417001017538',
    regist_date: '2021-10-22T05:19:09.000Z',
    sitetype: 'P',
    depositor: '강화수',
    deposit_date: '2021-10-22T05:18:25.000Z',
    settleprice: '10.00',
    step: '35',
    order_seq: '2021091417001017538',
    order_user_name: '강화수',
    order_phone: '--',
    order_cellphone: '010-3974-5175',
    order_email: 'iamsupermazinga@gmail.com',
    recipient_user_name: '강화수',
    recipient_phone: '--',
    recipient_cellphone: '010-3974-5175',
    recipient_email: 'iamsupermazinga@gmail.com',
    recipient_zipcode: '46291',
    recipient_address: '부산광역시 금정구 장전동 643-117 테라스파크',
    recipient_address_street: '부산광역시 금정구 장전온천천로 51 (테라스파크)',
    recipient_address_detail: '3131',
    memo: '',
    memoOriginal: '',
    totalPrice: '21.00',
    totalEa: 2,
    totalType: 2,
    totalShippingCost: '0.00',
    totalDeliveryCost: '0.00',
    items: [
      {
        goods_seq: 41,
        goods_name: 'test2',
        image: '/data/goods/1/2021/07/_temp_16266708888484thumbCart.png',
        item_seq: 27,
        shipping_seq: 24,
        shipping_set_name: '택배',
        shipping_type: 'free',
        shipping_method: 'delivery',
        shipping_group: '53_319_delivery',
        options: [
          {
            item_option_seq: 31,
            item_seq: 27,
            title1: '색상',
            option1: '블랙',
            ea: 1,
            step: '35',
            step35: 1,
            step45: 0,
            step55: 0,
            step65: 0,
            step75: 0,
            step85: 0,
            member_sale: '0.00',
            mobile_sale: null,
            price: '10.00',
            ori_price: '10.00',
          },
        ],
      },
      {
        goods_seq: 42,
        goods_name: 'test3',
        image: null,
        item_seq: 28,
        shipping_seq: 24,
        shipping_set_name: '택배',
        shipping_type: 'free',
        shipping_method: 'delivery',
        shipping_group: '53_319_delivery',
        options: [
          {
            item_option_seq: 32,
            item_seq: 28,
            title1: null,
            option1: '',
            ea: 1,
            step: '55',
            step35: 0,
            step45: 0,
            step55: 1,
            step65: 0,
            step75: 0,
            step85: 0,
            member_sale: '0.00',
            mobile_sale: null,
            price: '11.00',
            ori_price: '0.00',
          },
        ],
      },
    ],
    exports: [
      {
        export_code: 'D2110131194',
        bundle_export_code: '',
        export_date: '2021-10-12T15:00:00.000Z',
        complete_date: '2021-10-12T15:00:00.000Z',
        shipping_date: null,
        export_status: '55',
        delivery_company_code: 'code1',
        delivery_number: '1234',
        totalEa: 1,
        itemOptions: [
          {
            goods_name: 'test3',
            image: null,
            item_option_seq: 32,
            title1: null,
            option1: '',
            ea: 1,
            price: '11.00',
            step: '55',
          },
        ],
      },
    ],
    refunds: [],
    returns: [],
    shippings: [
      {
        shipping_seq: 24,
        shipping_set_name: '택배',
        shipping_type: 'free',
        shipping_method: 'delivery',
        shipping_group: '53_319_delivery',
        shipping_cost: '0.00',
        delivery_cost: '0.00',
        shippingCost: '0.00',
        deliveryCost: '0.00',
        items: [
          {
            goods_seq: 41,
            goods_name: 'test2',
            image: '/data/goods/1/2021/07/_temp_16266708888484thumbCart.png',
            item_seq: 27,
            shipping_seq: 24,
            shipping_set_name: '택배',
            shipping_type: 'free',
            shipping_method: 'delivery',
            shipping_group: '53_319_delivery',
            options: [
              {
                item_option_seq: 31,
                item_seq: 27,
                title1: '색상',
                option1: '블랙',
                ea: 1,
                step: '35',
                step35: 1,
                step45: 0,
                step55: 0,
                step65: 0,
                step75: 0,
                step85: 0,
                member_sale: '0.00',
                mobile_sale: null,
                price: '10.00',
                ori_price: '10.00',
              },
            ],
          },
          {
            goods_seq: 42,
            goods_name: 'test3',
            image: null,
            item_seq: 28,
            shipping_seq: 24,
            shipping_set_name: '택배',
            shipping_type: 'free',
            shipping_method: 'delivery',
            shipping_group: '53_319_delivery',
            options: [
              {
                item_option_seq: 32,
                item_seq: 28,
                title1: null,
                option1: '',
                ea: 1,
                step: '55',
                step35: 0,
                step45: 0,
                step55: 1,
                step65: 0,
                step75: 0,
                step85: 0,
                member_sale: '0.00',
                mobile_sale: null,
                price: '11.00',
                ori_price: '0.00',
              },
            ],
          },
        ],
      },
    ],
  },
  {
    shipping_seq: '14',
    id: '2021091015443317534',
    regist_date: '2021-09-10T06:44:33.000Z',
    sitetype: 'P',
    depositor: '전액할인',
    deposit_date: '2021-10-22T05:18:25.000Z',
    settleprice: '0.00',
    step: '45',
    order_seq: '2021091015443317534',
    order_user_name: '강화수',
    order_phone: '--',
    order_cellphone: '010-3974-5175',
    order_email: 'iamsupermazinga@gmail.com',
    recipient_user_name: '강화수',
    recipient_phone: '--',
    recipient_cellphone: '010-3974-5175',
    recipient_email: 'iamsupermazinga@gmail.com',
    recipient_zipcode: '46291',
    recipient_address: '부산광역시 금정구 장전동 643-117 테라스파크',
    recipient_address_street: '부산광역시 금정구 장전온천천로 51 (테라스파크)',
    recipient_address_detail: '313호',
    memo: '',
    memoOriginal: '',
    totalPrice: '0.00',
    totalEa: 1,
    totalType: 1,
    totalShippingCost: '0.00',
    totalDeliveryCost: '0.00',
    items: [
      {
        goods_seq: 42,
        goods_name: 'test2',
        image: null,
        item_seq: 15,
        shipping_seq: 14,
        shipping_set_name: '택배',
        shipping_type: 'free',
        shipping_method: 'delivery',
        shipping_group: '53_319_delivery',
        options: [
          {
            item_option_seq: 17,
            item_seq: 15,
            title1: null,
            option1: '',
            ea: 1,
            step: '45',
            step35: 0,
            step45: 1,
            step55: 0,
            step65: 0,
            step75: 0,
            step85: 0,
            member_sale: '0.00',
            mobile_sale: null,
            price: '0.00',
            ori_price: '0.00',
          },
        ],
      },
    ],
    exports: [
      {
        export_code: 'D2109122044',
        bundle_export_code: 'B2109122044',
        export_date: '2021-09-11T15:00:00.000Z',
        complete_date: '2021-09-11T15:00:00.000Z',
        shipping_date: null,
        export_status: '45',
        delivery_company_code: 'code0',
        delivery_number: '9876789',
        totalEa: 1,
        itemOptions: [
          {
            goods_name: 'test2',
            image: '/data/goods/1/2021/07/_temp_16266708888484thumbCart.png',
            item_option_seq: 16,
            title1: '색상',
            option1: '블랙',
            ea: 1,
            price: '10.00',
            step: '45',
          },
          {
            goods_name: 'test2',
            image: null,
            item_option_seq: 17,
            title1: null,
            option1: '',
            ea: 1,
            price: '0.00',
            step: '45',
          },
        ],
      },
    ],
    refunds: [],
    returns: [],
    shippings: [
      {
        shipping_seq: 14,
        shipping_set_name: '택배',
        shipping_type: 'free',
        shipping_method: 'delivery',
        shipping_group: '53_319_delivery',
        shipping_cost: '0.00',
        delivery_cost: '0.00',
        shippingCost: '0.00',
        deliveryCost: '0.00',
        items: [
          {
            goods_seq: 42,
            goods_name: 'test2',
            image: null,
            item_seq: 15,
            shipping_seq: 14,
            shipping_set_name: '택배',
            shipping_type: 'free',
            shipping_method: 'delivery',
            shipping_group: '53_319_delivery',
            options: [
              {
                item_option_seq: 17,
                item_seq: 15,
                title1: null,
                option1: '',
                ea: 1,
                step: '45',
                step35: 0,
                step45: 1,
                step55: 0,
                step65: 0,
                step75: 0,
                step85: 0,
                member_sale: '0.00',
                mobile_sale: null,
                price: '0.00',
                ori_price: '0.00',
              },
            ],
          },
        ],
      },
    ],
  },
  {
    shipping_seq: '21',
    id: '2021091416285017535',
    regist_date: '2021-10-22T05:19:09.000Z',
    sitetype: 'P',
    depositor: '강화수',
    deposit_date: '2021-10-22T05:17:41.000Z',
    settleprice: '1000.00',
    step: '55',
    order_seq: '2021091416285017535',
    order_user_name: '강화수',
    order_phone: '--',
    order_cellphone: '010-3974-5175',
    order_email: 'iamsupermazinga@gmail.com',
    recipient_user_name: '강화수',
    recipient_phone: '--',
    recipient_cellphone: '010-3974-5175',
    recipient_email: 'iamsupermazinga@gmail.com',
    recipient_zipcode: '46291',
    recipient_address: '부산광역시 금정구 장전동 643-117 테라스파크',
    recipient_address_street: '부산광역시 금정구 장전온천천로 51 (테라스파크)',
    recipient_address_detail: '0000호',
    memo: '',
    memoOriginal: '',
    totalPrice: '1000.00',
    totalEa: 1,
    totalType: 1,
    totalShippingCost: '0.00',
    totalDeliveryCost: '0.00',
    items: [
      {
        goods_seq: 41,
        goods_name: 'test2',
        image: '/data/goods/1/2021/07/_temp_16266708888484thumbCart.png',
        item_seq: 24,
        shipping_seq: 21,
        shipping_set_name: '택배',
        shipping_type: 'free',
        shipping_method: 'delivery',
        shipping_group: '53_319_delivery',
        options: [
          {
            item_option_seq: 28,
            item_seq: 24,
            title1: '색상',
            option1: '그레이',
            ea: 1,
            step: '55',
            step35: 0,
            step45: 0,
            step55: 1,
            step65: 0,
            step75: 0,
            step85: 0,
            member_sale: '0.00',
            mobile_sale: null,
            price: '1000.00',
            ori_price: '1000.00',
          },
        ],
      },
    ],
    exports: [
      {
        export_code: 'D2109141651',
        bundle_export_code: '',
        export_date: '2021-09-13T15:00:00.000Z',
        complete_date: '2021-09-13T15:00:00.000Z',
        shipping_date: null,
        export_status: '55',
        delivery_company_code: 'code1',
        delivery_number: '123456789',
        totalEa: 1,
        itemOptions: [
          {
            goods_name: 'test2',
            image: '/data/goods/1/2021/07/_temp_16266708888484thumbCart.png',
            item_option_seq: 28,
            title1: '색상',
            option1: '그레이',
            ea: 1,
            price: '1000.00',
            step: '55',
          },
        ],
      },
    ],
    refunds: [],
    returns: [],
    shippings: [
      {
        shipping_seq: 21,
        shipping_set_name: '택배',
        shipping_type: 'free',
        shipping_method: 'delivery',
        shipping_group: '53_319_delivery',
        shipping_cost: '0.00',
        delivery_cost: '0.00',
        shippingCost: '0.00',
        deliveryCost: '0.00',
        items: [
          {
            goods_seq: 41,
            goods_name: 'test2',
            image: '/data/goods/1/2021/07/_temp_16266708888484thumbCart.png',
            item_seq: 24,
            shipping_seq: 21,
            shipping_set_name: '택배',
            shipping_type: 'free',
            shipping_method: 'delivery',
            shipping_group: '53_319_delivery',
            options: [
              {
                item_option_seq: 28,
                item_seq: 24,
                title1: '색상',
                option1: '그레이',
                ea: 1,
                step: '55',
                step35: 0,
                step45: 0,
                step55: 1,
                step65: 0,
                step75: 0,
                step85: 0,
                member_sale: '0.00',
                mobile_sale: null,
                price: '1000.00',
                ori_price: '1000.00',
              },
            ],
          },
        ],
      },
    ],
  },
  {
    shipping_seq: '23',
    id: '2021091416562417537',
    regist_date: '2021-09-14T07:56:24.000Z',
    sitetype: 'P',
    depositor: '전액할인',
    deposit_date: '2021-10-22T05:18:25.000Z',
    settleprice: '0.00',
    step: '55',
    order_seq: '2021091416562417537',
    order_user_name: '강화수',
    order_phone: '--',
    order_cellphone: '010-3974-5175',
    order_email: 'iamsupermazinga@gmail.com',
    recipient_user_name: '강화수',
    recipient_phone: '--',
    recipient_cellphone: '010-3974-5175',
    recipient_email: 'iamsupermazinga@gmail.com',
    recipient_zipcode: '46291',
    recipient_address: '부산광역시 금정구 장전동 643-117 테라스파크',
    recipient_address_street: '부산광역시 금정구 장전온천천로 51 (테라스파크)',
    recipient_address_detail: '313호',
    memo: '',
    memoOriginal: '',
    totalPrice: '0.00',
    totalEa: 1,
    totalType: 1,
    totalShippingCost: '0.00',
    totalDeliveryCost: '0.00',
    items: [
      {
        goods_seq: 42,
        goods_name: 'test3',
        image: null,
        item_seq: 26,
        shipping_seq: 23,
        shipping_set_name: '택배',
        shipping_type: 'free',
        shipping_method: 'delivery',
        shipping_group: '53_319_delivery',
        options: [
          {
            item_option_seq: 30,
            item_seq: 26,
            title1: null,
            option1: '',
            ea: 1,
            step: '55',
            step35: 0,
            step45: 0,
            step55: 1,
            step65: 0,
            step75: 0,
            step85: 0,
            member_sale: '0.00',
            mobile_sale: null,
            price: '0.00',
            ori_price: '0.00',
          },
        ],
      },
    ],
    exports: [
      {
        export_code: 'D210914160',
        bundle_export_code: '',
        export_date: '2021-09-13T15:00:00.000Z',
        complete_date: '2021-09-13T15:00:00.000Z',
        shipping_date: null,
        export_status: '55',
        delivery_company_code: 'code2',
        delivery_number: '12345',
        totalEa: 1,
        itemOptions: [
          {
            goods_name: 'test2',
            image: '/data/goods/1/2021/07/_temp_16266708888484thumbCart.png',
            item_option_seq: 29,
            title1: '색상',
            option1: '블랙',
            ea: 1,
            price: '10.00',
            step: '55',
          },
          {
            goods_name: 'test3',
            image: null,
            item_option_seq: 30,
            title1: null,
            option1: '',
            ea: 1,
            price: '0.00',
            step: '55',
          },
        ],
      },
    ],
    refunds: [],
    returns: [],
    shippings: [
      {
        shipping_seq: 23,
        shipping_set_name: '택배',
        shipping_type: 'free',
        shipping_method: 'delivery',
        shipping_group: '53_319_delivery',
        shipping_cost: '0.00',
        delivery_cost: '0.00',
        shippingCost: '0.00',
        deliveryCost: '0.00',
        items: [
          {
            goods_seq: 42,
            goods_name: 'test3',
            image: null,
            item_seq: 26,
            shipping_seq: 23,
            shipping_set_name: '택배',
            shipping_type: 'free',
            shipping_method: 'delivery',
            shipping_group: '53_319_delivery',
            options: [
              {
                item_option_seq: 30,
                item_seq: 26,
                title1: null,
                option1: '',
                ea: 1,
                step: '55',
                step35: 0,
                step45: 0,
                step55: 1,
                step65: 0,
                step75: 0,
                step85: 0,
                member_sale: '0.00',
                mobile_sale: null,
                price: '0.00',
                ori_price: '0.00',
              },
            ],
          },
        ],
      },
    ],
  },
  {
    shipping_seq: '64',
    id: '2021101809410317533',
    regist_date: '2021-10-18T00:41:03.000Z',
    sitetype: 'P',
    depositor: '이지연',
    deposit_date: '2021-10-18T00:41:10.000Z',
    settleprice: '62700.00',
    step: '55',
    order_seq: '2021101809410317533',
    order_user_name: '이지연4',
    order_phone: '--',
    order_cellphone: '123-1234-1234',
    order_email: 'a1919361@gmail.com',
    recipient_user_name: '이지연4',
    recipient_phone: '--',
    recipient_cellphone: '123-1234-1234',
    recipient_email: 'a1919361@gmail.com',
    recipient_zipcode: '46291',
    recipient_address: '부산광역시 금정구 장전동 643-117 테라스파크',
    recipient_address_street: '부산광역시 금정구 장전온천천로 51 (테라스파크)',
    recipient_address_detail: '123',
    memo: '',
    memoOriginal: '',
    totalPrice: '20900.00',
    totalEa: 3,
    totalType: 1,
    totalShippingCost: '0.00',
    totalDeliveryCost: '0.00',
    items: [
      {
        goods_seq: 68,
        goods_name: '김통장육수 요리마법사',
        image: '/data/goods/1/2021/09/_temp_16324701714337thumbCart.jpg',
        item_seq: 71,
        shipping_seq: 64,
        shipping_set_name: '택배',
        shipping_type: 'free',
        shipping_method: 'delivery',
        shipping_group: '53_319_delivery',
        options: [
          {
            item_option_seq: 83,
            item_seq: 71,
            title1: '요리마법사',
            option1: '요리마법사 1.5L',
            ea: 3,
            step: '55',
            step35: -3,
            step45: 0,
            step55: 6,
            step65: 0,
            step75: 0,
            step85: 0,
            member_sale: '0.00',
            mobile_sale: null,
            price: '20900.00',
            ori_price: '20900.00',
          },
        ],
      },
    ],
    exports: [
      {
        export_code: 'D2110189108',
        bundle_export_code: '',
        export_date: '2021-10-17T15:00:00.000Z',
        complete_date: '2021-10-17T15:00:00.000Z',
        shipping_date: null,
        export_status: '55',
        delivery_company_code: 'code1',
        delivery_number: '123',
        totalEa: 3,
        itemOptions: [
          {
            goods_name: '김통장육수 요리마법사',
            image: '/data/goods/1/2021/09/_temp_16324701714337thumbCart.jpg',
            item_option_seq: 83,
            title1: '요리마법사',
            option1: '요리마법사 1.5L',
            ea: 3,
            price: '20900.00',
            step: '55',
          },
        ],
      },
      {
        export_code: 'D2110189109',
        bundle_export_code: '',
        export_date: '2021-10-17T15:00:00.000Z',
        complete_date: '2021-10-17T15:00:00.000Z',
        shipping_date: null,
        export_status: '55',
        delivery_company_code: 'code1',
        delivery_number: '123',
        totalEa: 3,
        itemOptions: [
          {
            goods_name: '김통장육수 요리마법사',
            image: '/data/goods/1/2021/09/_temp_16324701714337thumbCart.jpg',
            item_option_seq: 83,
            title1: '요리마법사',
            option1: '요리마법사 1.5L',
            ea: 3,
            price: '20900.00',
            step: '55',
          },
        ],
      },
    ],
    refunds: [],
    returns: [],
    shippings: [
      {
        shipping_seq: 64,
        shipping_set_name: '택배',
        shipping_type: 'free',
        shipping_method: 'delivery',
        shipping_group: '53_319_delivery',
        shipping_cost: '0.00',
        delivery_cost: '0.00',
        shippingCost: '0.00',
        deliveryCost: '0.00',
        items: [
          {
            goods_seq: 68,
            goods_name: '김통장육수 요리마법사',
            image: '/data/goods/1/2021/09/_temp_16324701714337thumbCart.jpg',
            item_seq: 71,
            shipping_seq: 64,
            shipping_set_name: '택배',
            shipping_type: 'free',
            shipping_method: 'delivery',
            shipping_group: '53_319_delivery',
            options: [
              {
                item_option_seq: 83,
                item_seq: 71,
                title1: '요리마법사',
                option1: '요리마법사 1.5L',
                ea: 3,
                step: '55',
                step35: -3,
                step45: 0,
                step55: 6,
                step65: 0,
                step75: 0,
                step85: 0,
                member_sale: '0.00',
                mobile_sale: null,
                price: '20900.00',
                ori_price: '20900.00',
              },
            ],
          },
        ],
      },
    ],
  },
  {
    shipping_seq: '112',
    id: '2021111614513017530',
    regist_date: '2021-11-16T05:51:30.000Z',
    sitetype: 'P',
    depositor: '',
    deposit_date: '2021-11-16T05:52:12.000Z',
    settleprice: '7505.00',
    step: '85',
    order_seq: '2021111614513017530',
    order_user_name: '전자결제테스트',
    order_phone: '--',
    order_cellphone: '010-8485-9285',
    order_email: 'kmotiv@naver.com',
    recipient_user_name: '전자결제테스트',
    recipient_phone: '--',
    recipient_cellphone: '010-8485-9285',
    recipient_email: '',
    recipient_zipcode: '50803',
    recipient_address: '경상남도 김해시 상동면 감노리 4-5',
    recipient_address_street: '경상남도 김해시 상동면 동북로 853',
    recipient_address_detail: '1',
    memo: '',
    memoOriginal: '',
    totalPrice: '7505.00',
    totalEa: 1,
    totalType: 1,
    totalShippingCost: '0.00',
    totalDeliveryCost: '0.00',
    items: [
      {
        goods_seq: 68,
        goods_name: '김통장육수 요리마법사',
        image: '/data/goods/1/2021/09/_temp_16324701714337thumbCart.jpg',
        item_seq: 131,
        shipping_seq: 112,
        shipping_set_name: '택배',
        shipping_type: 'free',
        shipping_method: 'delivery',
        shipping_group: '53_319_delivery',
        options: [
          {
            item_option_seq: 163,
            item_seq: 131,
            title1: '요리마법사',
            option1: '요리마법사 400g',
            ea: 1,
            step: '85',
            step35: 0,
            step45: 0,
            step55: 0,
            step65: 0,
            step75: 0,
            step85: 1,
            member_sale: '0.00',
            mobile_sale: null,
            price: '7505.00',
            ori_price: '7505.00',
          },
        ],
      },
    ],
    exports: [],
    refunds: [
      {
        refund_code: 'C2111161416',
        refund_type: 'cancel_payment',
        regist_date: '2021-11-16T05:54:44.000Z',
        refund_date: '2021-11-16T05:54:45.000Z',
        status: 'complete',
        refund_reason: '',
        manager_id: 'kwany',
        memail: 'kwany@onad.io',
        mcellphone: '01041765342',
        totalEa: '1',
        refund_goods_price: '7505.00',
        items: [
          {
            goods_name: '김통장육수 요리마법사',
            image: '/data/goods/1/2021/09/_temp_16324701714337thumbCart.jpg',
            refund_item_seq: 19,
            item_seq: 131,
            option_seq: 163,
            ea: 1,
            item_option_seq: 163,
            title1: '요리마법사',
            option1: '요리마법사 400g',
            step: '85',
            member_sale: '0.00',
            mobile_sale: null,
            price: '7505.00',
            ori_price: '7505.00',
          },
        ],
      },
    ],
    returns: [],
    shippings: [
      {
        shipping_seq: 112,
        shipping_set_name: '택배',
        shipping_type: 'free',
        shipping_method: 'delivery',
        shipping_group: '53_319_delivery',
        shipping_cost: '0.00',
        delivery_cost: '0.00',
        shippingCost: '0.00',
        deliveryCost: '0.00',
        items: [
          {
            goods_seq: 68,
            goods_name: '김통장육수 요리마법사',
            image: '/data/goods/1/2021/09/_temp_16324701714337thumbCart.jpg',
            item_seq: 131,
            shipping_seq: 112,
            shipping_set_name: '택배',
            shipping_type: 'free',
            shipping_method: 'delivery',
            shipping_group: '53_319_delivery',
            options: [
              {
                item_option_seq: 163,
                item_seq: 131,
                title1: '요리마법사',
                option1: '요리마법사 400g',
                ea: 1,
                step: '85',
                step35: 0,
                step45: 0,
                step55: 0,
                step65: 0,
                step75: 0,
                step85: 1,
                member_sale: '0.00',
                mobile_sale: null,
                price: '7505.00',
                ori_price: '7505.00',
              },
            ],
          },
        ],
      },
    ],
  },
  {
    shipping_seq: '117',
    id: '2021112219103917534',
    regist_date: '2021-11-22T10:10:39.000Z',
    sitetype: 'P',
    depositor: 'test',
    deposit_date: null,
    settleprice: '7505.00',
    step: '95',
    order_seq: '2021112219103917534',
    order_user_name: 'test',
    order_phone: '--',
    order_cellphone: '010-010-010',
    order_email: 'kmotiv@naver.com',
    recipient_user_name: 'test',
    recipient_phone: '--',
    recipient_cellphone: '010-010-010',
    recipient_email: '',
    recipient_zipcode: '50803',
    recipient_address: '경상남도 김해시 상동면 감노리 4-5',
    recipient_address_street: '경상남도 김해시 상동면 동북로 853',
    recipient_address_detail: '1',
    memo: '부재시 경비실에 맡겨 주세요.',
    memoOriginal: '부재시 경비실에 맡겨 주세요.',
    totalPrice: '7505.00',
    totalEa: 1,
    totalType: 1,
    totalShippingCost: '0.00',
    totalDeliveryCost: '0.00',
    items: [
      {
        goods_seq: 68,
        goods_name: '김통장육수 요리마법사',
        image: '/data/goods/1/2021/09/_temp_16324701714337thumbCart.jpg',
        item_seq: 136,
        shipping_seq: 117,
        shipping_set_name: '택배',
        shipping_type: 'free',
        shipping_method: 'delivery',
        shipping_group: '53_319_delivery',
        options: [
          {
            item_option_seq: 168,
            item_seq: 136,
            title1: '요리마법사',
            option1: '요리마법사 400g',
            ea: 1,
            step: '95',
            step35: 0,
            step45: 0,
            step55: 0,
            step65: 0,
            step75: 0,
            step85: 0,
            member_sale: '0.00',
            mobile_sale: null,
            price: '7505.00',
            ori_price: '7505.00',
          },
        ],
      },
    ],
    exports: [],
    refunds: [],
    returns: [],
    shippings: [
      {
        shipping_seq: 117,
        shipping_set_name: '택배',
        shipping_type: 'free',
        shipping_method: 'delivery',
        shipping_group: '53_319_delivery',
        shipping_cost: '0.00',
        delivery_cost: '0.00',
        shippingCost: '0.00',
        deliveryCost: '0.00',
        items: [
          {
            goods_seq: 68,
            goods_name: '김통장육수 요리마법사',
            image: '/data/goods/1/2021/09/_temp_16324701714337thumbCart.jpg',
            item_seq: 136,
            shipping_seq: 117,
            shipping_set_name: '택배',
            shipping_type: 'free',
            shipping_method: 'delivery',
            shipping_group: '53_319_delivery',
            options: [
              {
                item_option_seq: 168,
                item_seq: 136,
                title1: '요리마법사',
                option1: '요리마법사 400g',
                ea: 1,
                step: '95',
                step35: 0,
                step45: 0,
                step55: 0,
                step65: 0,
                step75: 0,
                step85: 0,
                member_sale: '0.00',
                mobile_sale: null,
                price: '7505.00',
                ori_price: '7505.00',
              },
            ],
          },
        ],
      },
    ],
  },
  {
    shipping_seq: '71',
    id: '2021101914134817533',
    regist_date: '2021-10-19T05:13:48.000Z',
    sitetype: 'P',
    depositor: '이지연',
    deposit_date: '2021-10-19T06:35:03.000Z',
    settleprice: '265225.00',
    step: '55',
    order_seq: '2021101914134817533',
    order_user_name: '이지연4',
    order_phone: '--',
    order_cellphone: '123-1234-1234',
    order_email: 'a1919361@gmail.com',
    recipient_user_name: '이지연4',
    recipient_phone: '--',
    recipient_cellphone: '123-1234-1234',
    recipient_email: 'a1919361@gmail.com',
    recipient_zipcode: '46291',
    recipient_address: '부산광역시 금정구 장전동 643-117 테라스파크',
    recipient_address_street: '부산광역시 금정구 장전온천천로 51 (테라스파크)',
    recipient_address_detail: '123',
    memo: '',
    memoOriginal: '',
    totalPrice: '36860.00',
    totalEa: 7,
    totalType: 3,
    totalShippingCost: '0.00',
    totalDeliveryCost: '0.00',
    items: [
      {
        goods_seq: 68,
        goods_name: '김통장육수 요리마법사',
        image: '/data/goods/1/2021/09/_temp_16324701714337thumbCart.jpg',
        item_seq: 85,
        shipping_seq: 71,
        shipping_set_name: '택배',
        shipping_type: 'free',
        shipping_method: 'delivery',
        shipping_group: '53_319_delivery',
        options: [
          {
            item_option_seq: 103,
            item_seq: 85,
            title1: '요리마법사',
            option1: '요리마법사 400g',
            ea: 3,
            step: '55',
            step35: 0,
            step45: 0,
            step55: 3,
            step65: 0,
            step75: 0,
            step85: 0,
            member_sale: '0.00',
            mobile_sale: null,
            price: '7505.00',
            ori_price: '7505.00',
          },
          {
            item_option_seq: 104,
            item_seq: 85,
            title1: '요리마법사',
            option1: '매운 요리마법사 400g',
            ea: 2,
            step: '55',
            step35: 0,
            step45: 0,
            step55: 2,
            step65: 0,
            step75: 0,
            step85: 0,
            member_sale: '0.00',
            mobile_sale: null,
            price: '8455.00',
            ori_price: '8455.00',
          },
          {
            item_option_seq: 105,
            item_seq: 85,
            title1: '요리마법사',
            option1: '요리마법사 1.5L',
            ea: 2,
            step: '55',
            step35: 0,
            step45: 0,
            step55: 2,
            step65: 0,
            step75: 0,
            step85: 0,
            member_sale: '0.00',
            mobile_sale: null,
            price: '20900.00',
            ori_price: '20900.00',
          },
        ],
      },
    ],
    exports: [
      {
        export_code: 'D21101917120',
        bundle_export_code: '',
        export_date: '2021-10-18T15:00:00.000Z',
        complete_date: '2021-10-18T15:00:00.000Z',
        shipping_date: null,
        export_status: '55',
        delivery_company_code: 'code0',
        delivery_number: '1234567890',
        totalEa: 7,
        itemOptions: [
          {
            goods_name: '김통장육수 요리마법사',
            image: '/data/goods/1/2021/09/_temp_16324701714337thumbCart.jpg',
            item_option_seq: 103,
            title1: '요리마법사',
            option1: '요리마법사 400g',
            ea: 3,
            price: '7505.00',
            step: '55',
          },
          {
            goods_name: '김통장육수 요리마법사',
            image: '/data/goods/1/2021/09/_temp_16324701714337thumbCart.jpg',
            item_option_seq: 104,
            title1: '요리마법사',
            option1: '매운 요리마법사 400g',
            ea: 2,
            price: '8455.00',
            step: '55',
          },
          {
            goods_name: '김통장육수 요리마법사',
            image: '/data/goods/1/2021/09/_temp_16324701714337thumbCart.jpg',
            item_option_seq: 105,
            title1: '요리마법사',
            option1: '요리마법사 1.5L',
            ea: 2,
            price: '20900.00',
            step: '55',
          },
        ],
      },
    ],
    refunds: [],
    returns: [],
    shippings: [
      {
        shipping_seq: 71,
        shipping_set_name: '택배',
        shipping_type: 'free',
        shipping_method: 'delivery',
        shipping_group: '53_319_delivery',
        shipping_cost: '0.00',
        delivery_cost: '0.00',
        shippingCost: '0.00',
        deliveryCost: '0.00',
        items: [
          {
            goods_seq: 68,
            goods_name: '김통장육수 요리마법사',
            image: '/data/goods/1/2021/09/_temp_16324701714337thumbCart.jpg',
            item_seq: 85,
            shipping_seq: 71,
            shipping_set_name: '택배',
            shipping_type: 'free',
            shipping_method: 'delivery',
            shipping_group: '53_319_delivery',
            options: [
              {
                item_option_seq: 103,
                item_seq: 85,
                title1: '요리마법사',
                option1: '요리마법사 400g',
                ea: 3,
                step: '55',
                step35: 0,
                step45: 0,
                step55: 3,
                step65: 0,
                step75: 0,
                step85: 0,
                member_sale: '0.00',
                mobile_sale: null,
                price: '7505.00',
                ori_price: '7505.00',
              },
              {
                item_option_seq: 104,
                item_seq: 85,
                title1: '요리마법사',
                option1: '매운 요리마법사 400g',
                ea: 2,
                step: '55',
                step35: 0,
                step45: 0,
                step55: 2,
                step65: 0,
                step75: 0,
                step85: 0,
                member_sale: '0.00',
                mobile_sale: null,
                price: '8455.00',
                ori_price: '8455.00',
              },
              {
                item_option_seq: 105,
                item_seq: 85,
                title1: '요리마법사',
                option1: '요리마법사 1.5L',
                ea: 2,
                step: '55',
                step35: 0,
                step45: 0,
                step55: 2,
                step65: 0,
                step75: 0,
                step85: 0,
                member_sale: '0.00',
                mobile_sale: null,
                price: '20900.00',
                ori_price: '20900.00',
              },
            ],
          },
        ],
      },
    ],
  },
];

describe('OrderSheetGenerator', () => {
  it('must return true', async () => {
    const g = new OrderSpreadSheetGenerator();
    const d = g.createXLSX(dummies);
    console.log(d);
    await g.download('test.xlsx', d);
  });

  // test('클래스 옵션 적용1', async () => {
  //   const g = new OrderSpreadSheetGenerator({
  //     sheetName: '테스트시트',
  //     disabledColumnHeaders: ['주문일'],
  //   });
  //   const d = g.createXLSX(dummies);
  //   console.log(d);
  // });
});
