export const ACCESS_TOKEN_EXPIRE_TIME = '15m';
export const ACCESS_TOKEN_EXPIRE_TIME_INT = 15 * 60 * 1000;
export const ADMIN_ACCESS_TOKEN_EXPIRE_TIME_INT = 24 * 60 * 60 * 1000;
export const REFRESH_TOKEN_EXPIRE_TIME = '30m';
export const AUTO_LOGIN_EXPIRE_TIME = '14d';
export const COOKIE_EXPIRE_TIME = 1800 * 1000;
export const COOKIE_AUTO_LOGIN_EXPIRE_TIME = 14 * 24 * 60 * 60 * 1000;
export const ACCESS_TOKEN_HEADER_KEY = 'X-wt-Access-Token';
export const REFRESH_TOKEN_HEADER_KEY = 'refresh_token';
